// This file is automatically generated by MARGEE.
// This file should not be changed.

declare global {
    interface ARG_BASE<T extends string> {
        readonly type: T;
    }
    interface ARG_CONST_BASE<T extends string, V> extends ARG_BASE<T> {
        readonly value: V;
    }
    interface ARG_VAL_BASE<T extends string> extends ARG_BASE<T> {
        readonly offset?: number;
    }
    export type ARG_CONST_SINT = ARG_CONST_BASE<'ARG_CONST_SINT', number>;
    export type ARG_CONST_INT = ARG_CONST_BASE<'ARG_CONST_INT', number>;
    export type ARG_CONST_DINT = ARG_CONST_BASE<'ARG_CONST_DINT', number>;
    export type ARG_CONST_USINT = ARG_CONST_BASE<'ARG_CONST_USINT', number>;
    export type ARG_CONST_UINT = ARG_CONST_BASE<'ARG_CONST_UINT', number>;
    export type ARG_CONST_UDINT = ARG_CONST_BASE<'ARG_CONST_UDINT', number>;
    export type ARG_CONST_REAL = ARG_CONST_BASE<'ARG_CONST_REAL', number>;
    export type ARG_CONST_ARRAY_SINT = ARG_CONST_BASE<'ARG_CONST_ARRAY_SINT', number[]>;
    export type ARG_CONST_ARRAY_DINT = ARG_CONST_BASE<'ARG_CONST_ARRAY_DINT', number[]>;
    export type ARG_CONST_ARRAY_INT = ARG_CONST_BASE<'ARG_CONST_ARRAY_INT', number[]>;
    export type ARG_CONST_ARRAY_USINT = ARG_CONST_BASE<'ARG_CONST_ARRAY_USINT', number[]>;
    export type ARG_CONST_ARRAY_UINT = ARG_CONST_BASE<'ARG_CONST_ARRAY_UINT', number[]>;
    export type ARG_CONST_ARRAY_UDINT = ARG_CONST_BASE<'ARG_CONST_ARRAY_UDINT', number[]>;
    export type ARG_CONST_ARRAY_REAL = ARG_CONST_BASE<'ARG_CONST_ARRAY_REAL', number[]>;
    export type ARG_VAL_SINT = ARG_VAL_BASE<'ARG_VAL_SINT'>;
    export type ARG_VAL_INT = ARG_VAL_BASE<'ARG_VAL_INT'>;
    export type ARG_VAL_DINT = ARG_VAL_BASE<'ARG_VAL_DINT'>;
    export type ARG_VAL_USINT = ARG_VAL_BASE<'ARG_VAL_USINT'>;
    export type ARG_VAL_UINT = ARG_VAL_BASE<'ARG_VAL_UINT'>;
    export type ARG_VAL_UDINT = ARG_VAL_BASE<'ARG_VAL_UDINT'>;
    export type ARG_VAL_REAL = ARG_VAL_BASE<'ARG_VAL_REAL'>;
    export type ARG_VAL_ARRAY_SINT = ARG_VAL_BASE<'ARG_VAL_ARRAY_SINT'> & {
        readonly arrayLength: number;
    };
    export type ARG_VAL_ARRAY_DINT = ARG_VAL_BASE<'ARG_VAL_ARRAY_DINT'> & {
        readonly arrayLength: number;
    };
    export type ARG_VAL_ARRAY_INT = ARG_VAL_BASE<'ARG_VAL_ARRAY_INT'> & {
        readonly arrayLength: number;
    };
    export type ARG_VAL_ARRAY_USINT = ARG_VAL_BASE<'ARG_VAL_ARRAY_USINT'> & {
        readonly arrayLength: number;
    };
    export type ARG_VAL_ARRAY_UINT = ARG_VAL_BASE<'ARG_VAL_ARRAY_UINT'> & {
        readonly arrayLength: number;
    };
    export type ARG_VAL_ARRAY_UDINT = ARG_VAL_BASE<'ARG_VAL_ARRAY_UDINT'> & {
        readonly arrayLength: number;
    };
    export type ARG_VAL_ARRAY_REAL = ARG_VAL_BASE<'ARG_VAL_ARRAY_REAL'> & {
        readonly arrayLength: number;
    };
    export type ARG_CONST_SIGNED = ARG_CONST_SINT | ARG_CONST_INT | ARG_CONST_DINT;
    export type ARG_CONST_UNSIGNED = ARG_CONST_USINT | ARG_CONST_UINT | ARG_CONST_UDINT;
    export type ARG_CONST_NUMERICAL = ARG_CONST_SIGNED | ARG_CONST_UNSIGNED | ARG_CONST_REAL;
    export type ARG_CONST_ARRAY_SIGNED = ARG_CONST_ARRAY_SINT | ARG_CONST_ARRAY_INT | ARG_CONST_ARRAY_DINT;
    export type ARG_CONST_ARRAY_UNSIGNED = ARG_CONST_ARRAY_USINT | ARG_CONST_ARRAY_UINT | ARG_CONST_ARRAY_UDINT;
    export type ARG_CONST_ARRAY_NUMERICAL = ARG_CONST_ARRAY_SIGNED | ARG_CONST_ARRAY_UNSIGNED | ARG_CONST_ARRAY_REAL;
    export type ARG_CONST = ARG_CONST_NUMERICAL | ARG_CONST_ARRAY_NUMERICAL;
    export type ARG_VAL_SIGNED = ARG_VAL_SINT | ARG_VAL_INT | ARG_VAL_DINT;
    export type ARG_VAL_UNSIGNED = ARG_VAL_USINT | ARG_VAL_UINT | ARG_VAL_UDINT;
    export type ARG_VAL_NUMERICAL = ARG_VAL_SIGNED | ARG_VAL_UNSIGNED | ARG_VAL_REAL;
    export type ARG_VAL_ARRAY_SIGNED = ARG_VAL_ARRAY_SINT | ARG_VAL_ARRAY_INT | ARG_VAL_ARRAY_DINT;
    export type ARG_VAL_ARRAY_UNSIGNED = ARG_VAL_ARRAY_USINT | ARG_VAL_ARRAY_UINT | ARG_VAL_ARRAY_UDINT;
    export type ARG_VAL_ARRAY_NUMERICAL = ARG_VAL_ARRAY_SIGNED | ARG_VAL_ARRAY_UNSIGNED | ARG_VAL_ARRAY_REAL;
    export type ARG_VAL = ARG_VAL_NUMERICAL | ARG_VAL_ARRAY_NUMERICAL;
    export type ARG = ARG_CONST | ARG_VAL;
    export abstract class RUNTIME_ELEMENT {
        abstract readonly root: HTMLElement;
        content?: HTMLElement;
        abstract render(...args: (ARG | undefined)[]): void;
    }
    class runtime {
        get isRendered(): boolean;
        readGOM(uid: number, inst: number): Promise<Uint8Array | undefined>;
        readGOMs(objs: {
            uid: number;
            inst: number;
        }[]): Promise<Uint8Array[] | undefined>;
        writeGOM(uid: number, inst: number, value: Uint8Array): Promise<boolean>;
        getImageStr(name: string): string | undefined;
        changeScreen(index: number): void;
        currentScreen(): number;
        screenNames(): string[];
        getGOMval(uid: number, inst: number, callBack?: (value: Uint8Array) => void): void;
        setGOMval(uid: number, inst: number, data: Uint8Array | number, callBack?: () => void): void;
        get(descriptor: ARG_VAL_NUMERICAL | ARG_CONST_NUMERICAL): number;
        get(descriptor: ARG_VAL_NUMERICAL | ARG_CONST_NUMERICAL, format: 'number'): number;
        get(descriptor: ARG_VAL_NUMERICAL | ARG_CONST_NUMERICAL, format: 'Uint8Array'): Uint8Array;
        get(descriptor: ARG_VAL_ARRAY_NUMERICAL | ARG_CONST_ARRAY_NUMERICAL): number[];
        get(descriptor: ARG_VAL_ARRAY_NUMERICAL | ARG_CONST_ARRAY_NUMERICAL, format: 'number[]'): number[];
        get(descriptor: ARG_VAL_ARRAY_NUMERICAL | ARG_CONST_ARRAY_NUMERICAL, format: 'Uint8Array'): Uint8Array;
        get(descriptor: ARG_VAL_ARRAY_USINT | ARG_CONST_ARRAY_USINT, format: 'string'): string;
        get(descriptor: ARG_VAL_ARRAY_USINT | ARG_CONST_ARRAY_USINT, format: 'formattedString'): string;
        get(descriptor: ARG_VAL_NUMERICAL | ARG_CONST_NUMERICAL | undefined): number | undefined;
        get(descriptor: ARG_VAL_NUMERICAL | ARG_CONST_NUMERICAL | undefined, format: 'number'): number | undefined;
        get(descriptor: ARG_VAL_NUMERICAL | ARG_CONST_NUMERICAL | undefined, format: 'Uint8Array'): Uint8Array | undefined;
        get(descriptor: ARG_VAL_ARRAY_NUMERICAL | ARG_CONST_ARRAY_NUMERICAL | undefined): number[] | undefined;
        get(descriptor: ARG_VAL_ARRAY_NUMERICAL | ARG_CONST_ARRAY_NUMERICAL | undefined, format: 'number[]'): number[] | undefined;
        get(descriptor: ARG_VAL_ARRAY_NUMERICAL | ARG_CONST_ARRAY_NUMERICAL | undefined, format: 'Uint8Array'): Uint8Array | undefined;
        get(descriptor: ARG_VAL_ARRAY_USINT | ARG_CONST_ARRAY_USINT | undefined, format: 'string'): string | undefined;
        get(descriptor: ARG_VAL_ARRAY_USINT | ARG_CONST_ARRAY_USINT | undefined, format: 'formattedString'): string | undefined;
        getReal(descriptor: ARG_VAL_REAL | ARG_CONST_REAL): number;
        getReal(descriptor: ARG_VAL_REAL | ARG_CONST_REAL, format: 'Uint8Array'): Uint8Array;
        getReal(descriptor: ARG_VAL_REAL | ARG_CONST_REAL, format: 'number'): number;
        getDint(descriptor: ARG_VAL_DINT | ARG_CONST_DINT): number;
        getDint(descriptor: ARG_VAL_DINT | ARG_CONST_DINT, format: 'Uint8Array'): Uint8Array;
        getDint(descriptor: ARG_VAL_DINT | ARG_CONST_DINT, format: 'number'): number | Uint8Array;
        getInt(descriptor: ARG_VAL_INT | ARG_CONST_INT): number;
        getInt(descriptor: ARG_VAL_INT | ARG_CONST_INT, format: 'Uint8Array'): Uint8Array;
        getInt(descriptor: ARG_VAL_INT | ARG_CONST_INT, format: 'number'): number | Uint8Array;
        getSint(descriptor: ARG_VAL_SINT | ARG_CONST_SINT): number;
        getSint(descriptor: ARG_VAL_SINT | ARG_CONST_SINT, format: 'Uint8Array'): Uint8Array;
        getSint(descriptor: ARG_VAL_SINT | ARG_CONST_SINT, format: 'number'): number | Uint8Array;
        getUdint(descriptor: ARG_VAL_UDINT | ARG_CONST_UDINT): number;
        getUdint(descriptor: ARG_VAL_UDINT | ARG_CONST_UDINT, format: 'Uint8Array'): Uint8Array;
        getUdint(descriptor: ARG_VAL_UDINT | ARG_CONST_UDINT, format: 'number'): number | Uint8Array;
        getUint(descriptor: ARG_VAL_UINT | ARG_CONST_UINT): number;
        getUint(descriptor: ARG_VAL_UINT | ARG_CONST_UINT, format: 'Uint8Array'): Uint8Array;
        getUint(descriptor: ARG_VAL_UINT | ARG_CONST_UINT, format: 'number'): number | Uint8Array;
        getUsint(descriptor: ARG_VAL_USINT | ARG_CONST_USINT): number;
        getUsint(descriptor: ARG_VAL_USINT | ARG_CONST_USINT, format: 'Uint8Array'): Uint8Array;
        getUsint(descriptor: ARG_VAL_USINT | ARG_CONST_USINT, format: 'number'): number | Uint8Array;
        getArrayReal(descriptor: ARG_VAL_ARRAY_REAL | ARG_CONST_ARRAY_REAL): number[];
        getArrayReal(descriptor: ARG_VAL_ARRAY_REAL | ARG_CONST_ARRAY_REAL, format: 'number[]'): number[];
        getArrayReal(descriptor: ARG_VAL_ARRAY_REAL | ARG_CONST_ARRAY_REAL, format: 'Uint8Array'): Uint8Array;
        getArrayDint(descriptor: ARG_VAL_ARRAY_DINT | ARG_CONST_ARRAY_DINT): number[];
        getArrayDint(descriptor: ARG_VAL_ARRAY_DINT | ARG_CONST_ARRAY_DINT, format: 'number[]'): number[];
        getArrayDint(descriptor: ARG_VAL_ARRAY_DINT | ARG_CONST_ARRAY_DINT, format: 'Uint8Array'): Uint8Array;
        getArrayInt(descriptor: ARG_VAL_ARRAY_INT | ARG_CONST_ARRAY_INT): number[];
        getArrayInt(descriptor: ARG_VAL_ARRAY_INT | ARG_CONST_ARRAY_INT, format: 'number[]'): number[];
        getArrayInt(descriptor: ARG_VAL_ARRAY_INT | ARG_CONST_ARRAY_INT, format: 'Uint8Array'): Uint8Array;
        getArraySint(descriptor: ARG_VAL_ARRAY_SINT | ARG_CONST_ARRAY_SINT): number[];
        getArraySint(descriptor: ARG_VAL_ARRAY_SINT | ARG_CONST_ARRAY_SINT, format: 'number[]'): number[];
        getArraySint(descriptor: ARG_VAL_ARRAY_SINT | ARG_CONST_ARRAY_SINT, format: 'Uint8Array'): Uint8Array;
        getArrayUdint(descriptor: ARG_VAL_ARRAY_UDINT | ARG_CONST_ARRAY_UDINT): number[];
        getArrayUdint(descriptor: ARG_VAL_ARRAY_UDINT | ARG_CONST_ARRAY_UDINT, format: 'number[]'): number[];
        getArrayUdint(descriptor: ARG_VAL_ARRAY_UDINT | ARG_CONST_ARRAY_UDINT, format: 'Uint8Array'): Uint8Array;
        getArrayUint(descriptor: ARG_VAL_ARRAY_UINT | ARG_CONST_ARRAY_UINT): number[];
        getArrayUint(descriptor: ARG_VAL_ARRAY_UINT | ARG_CONST_ARRAY_UINT, format: 'number[]'): number[];
        getArrayUint(descriptor: ARG_VAL_ARRAY_UINT | ARG_CONST_ARRAY_UINT, format: 'Uint8Array'): Uint8Array;
        getArrayUsint(descriptor: ARG_VAL_ARRAY_USINT | ARG_CONST_ARRAY_USINT): number[];
        getArrayUsint(descriptor: ARG_VAL_ARRAY_USINT | ARG_CONST_ARRAY_USINT, format: 'number[]'): number[];
        getArrayUsint(descriptor: ARG_VAL_ARRAY_USINT | ARG_CONST_ARRAY_USINT, format: 'Uint8Array'): Uint8Array;
        getArrayUsint(descriptor: ARG_VAL_ARRAY_USINT | ARG_CONST_ARRAY_USINT, format: 'string'): string;
        getArrayUsint(descriptor: ARG_VAL_ARRAY_USINT | ARG_CONST_ARRAY_USINT, format: 'formattedString'): string;
        set(descriptor: ARG_VAL_NUMERICAL, value: number): void;
        set(descriptor: ARG_VAL_ARRAY_NUMERICAL, value: number[] | Uint8Array): void;
        set(descriptor: ARG_VAL_ARRAY_USINT, value: string): void;
        setReal(descriptor: ARG_VAL_REAL, value: number): void;
        setDint(descriptor: ARG_VAL_DINT, value: number): void;
        setInt(descriptor: ARG_VAL_INT, value: number): void;
        setSint(descriptor: ARG_VAL_SINT, value: number): void;
        setUdint(descriptor: ARG_VAL_UDINT, value: number): void;
        setUint(descriptor: ARG_VAL_UINT, value: number): void;
        setUsint(descriptor: ARG_VAL_USINT, value: number): void;
        setArrayReal(descriptor: ARG_VAL_ARRAY_REAL, value: number[] | Uint8Array): void;
        setArrayDint(descriptor: ARG_VAL_ARRAY_DINT, value: number[] | Uint8Array): void;
        setArrayInt(descriptor: ARG_VAL_ARRAY_INT, value: number[] | Uint8Array): void;
        setArraySint(descriptor: ARG_VAL_ARRAY_SINT, value: number[] | Uint8Array): void;
        setArrayUdint(descriptor: ARG_VAL_ARRAY_UDINT, value: number[] | Uint8Array): void;
        setArrayUint(descriptor: ARG_VAL_ARRAY_UINT, value: number[] | Uint8Array): void;
        setArrayUsint(descriptor: ARG_VAL_ARRAY_USINT, value: number[] | Uint8Array | string): void;
        signIn(password: string): Promise<number>;
        signOut(): Promise<void>;
        changePassword(userId: number, newPassword: string): Promise<{
            result: true;
        } | {
            result: false;
            reason: string;
        }>;
        currentUser(): number;
    }
    export let HMI_RUNTIME: runtime;
    export const bufferToString: (buffer: Uint8Array | number[], terminateOnNull: boolean) => string;
    export const stringToBuffer: (str: string) => Uint8Array<ArrayBufferLike>;
    export const fromBytesFloat: (arr: Uint8Array, litteEndian?: boolean) => number;
    export const fromBytesInt16: (arr: Uint8Array, litteEndian?: boolean) => number;
    export const fromBytesInt32: (arr: Uint8Array, litteEndian?: boolean) => number;
    export const fromBytesInt8: (arr: Uint8Array) => number;
    export const fromBytesUint16: (arr: Uint8Array, litteEndian?: boolean) => number;
    export const fromBytesUint32: (arr: Uint8Array, litteEndian?: boolean) => number;
    export const toBytesFloat: (num: number, littleEndian?: boolean) => Uint8Array<ArrayBufferLike>;
    export const toBytesInt16: (num: number, littleEndian?: boolean) => Uint8Array<ArrayBufferLike>;
    export const toBytesInt32: (num: number, littleEndian?: boolean) => Uint8Array<ArrayBufferLike>;
    export const toBytesInt8: (num: number) => Uint8Array<ArrayBufferLike>;
    export const toBytesUint16: (num: number, littleEndian?: boolean) => Uint8Array<ArrayBufferLike>;
    export const toBytesUint32: (num: number, littleEndian?: boolean) => Uint8Array<ArrayBufferLike>;
    export const toBytesUint8: (num: number) => Uint8Array<ArrayBufferLike>;
    export const fromBytesFloatArray: (arr: Uint8Array, litteEndian?: boolean) => number[];
    export const fromBytesInt16Array: (arr: Uint8Array, litteEndian?: boolean) => number[];
    export const fromBytesInt32Array: (arr: Uint8Array, litteEndian?: boolean) => number[];
    export const fromBytesInt8Array: (arr: Uint8Array, litteEndian?: boolean) => number[];
    export const fromBytesUint16Array: (arr: Uint8Array, litteEndian?: boolean) => number[];
    export const fromBytesUint32Array: (arr: Uint8Array, litteEndian?: boolean) => number[];
    export const fromBytesUint8Array: (arr: Uint8Array, litteEndian?: boolean) => number[];
    export const toBytesFloatArray: (arr: number[], littleEndian?: boolean) => Uint8Array<ArrayBufferLike>;
    export const toBytesInt16Array: (arr: number[], littleEndian?: boolean) => Uint8Array<ArrayBufferLike>;
    export const toBytesInt32Array: (arr: number[], littleEndian?: boolean) => Uint8Array<ArrayBufferLike>;
    export const toBytesInt8Array: (arr: number[]) => Uint8Array<ArrayBufferLike>;
    export const toBytesUint16Array: (arr: number[], littleEndian?: boolean) => Uint8Array<ArrayBufferLike>;
    export const toBytesUint32Array: (arr: number[], littleEndian?: boolean) => Uint8Array<ArrayBufferLike>;
    export const toBytesUint8Array: (arr: number[]) => Uint8Array<ArrayBufferLike>;
    export const compareBuffers: (a: Uint8Array, b: Uint8Array) => boolean;
    export const fromBytesUint8: (arr: Uint8Array) => number;
    export const int16ToBigEndian: (value: number) => number;
    export const int16ToLittleEndian: (value: number) => number;
    export const int32ToBigEndian: (value: number) => number;
    export const int32ToLittleEndian: (value: number) => number;
    export const concatBuffers: (...buffers: Uint8Array[]) => Uint8Array<ArrayBuffer>;
}

export {};
